version: '3'
services:

  deno:
    image: denoland/deno:1.38.0
    container_name: deno
    hostname: rustup.horse.local
    domainname: horse.local
    tty: true
    command: "tail -f /dev/null"
    volumes:
      - ${DENO_CONTAINER_FOLDER_PATH}:/deno
    working_dir: /deno
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 127.0.0.11
    ports:
      - "${DENO_CONTAINER_PORT}:8000"
    networks:
      racing_devEnvLocal:


  mariadb:
    image: mariadb:10.4
    container_name: deno_mariadb
    dns_search: devEnv.local
    hostname: mariadb.devEnv.local
    domainname: devEnv.local
    restart: on-failure:2
    # Check if Db is switch on
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
      interval: 120s
      timeout: 1s
      retries: 3
    networks:
      racing_devEnvLocal:
        aliases:
          - mariadb.devEnv.local
          - mariadb104.devEnv.local
    volumes:
      - ${DB_CONTAINER_FOLDER_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_CONTAINER_PORT}:3306"


networks:
  racing_devEnvLocal:
        driver: bridge